# version: "3"
networks:
  default:
    name: docker-hadoop-poc
# networks:
#   docker-hadoop-poc:
#     driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - /dev/hdd/hadoop_data/namenode:/hadoop/dfs/name
      # - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
      - "8020:8020"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    volumes:
      # - datanode:/hadoop/dfs/data
      - /dev/hdd/hadoop_data/datanode:/hadoop/dfs/data

    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      # HDFS_CONF_dfs_datanode_data_dir: "file:///dev/hdd/hadoop_data"
    ports:
      - "9864:9864"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    
    ports:
      - "8032:8032"
      - "8088:8088"


  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    ## 
    ## docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' resourcemanager 나온 주소 입력
    # extra_hosts:
      # - "resourcemanager:172.18.0.7:8088"
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"


  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"

  hive-metastore-mysql:
    image: mysql:8.0.21
    container_name: hive-metastore-mysql
    hostname: hive-metastore-mysql
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"

  hive-server:
    image: kadensungbincho/hadoop-hive-mysql:hive3.1.2-hadoop3.2.1-java8
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - resourcemanager
      - nodemanager
      - historyserver
      - hive-metastore
    volumes:
      - ./dummy_data:/opt/dummy_data
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
      DUMMY_DATA: 1
    ports:
      - "10000:10000"

  hive-metastore:
    image: kadensungbincho/hadoop-hive-mysql:hive3.1.2-hadoop3.2.1-java8
    container_name: hive-metastore
    hostname: hive-metastore
    depends_on:
      - hive-metastore-mysql
    env_file:
      - hadoop.env
    command: [ "startup.sh", "metastore" ]
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-mysql:3306"
    ports:
      - "9083:9083"

  zookeeper:
    image: zookeeper:3.4.14
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181

####
## 20241007 hbase 추가 
  hbase-master:
    image: harisekhon/hbase:1.2
    container_name: hbase-master
    hostname: hbase-master
    environment:
      - HBASE_MANAGES_ZK=false
      - HBASE_CONF_hbase_rootdir=hdfs://namenode:8020/hbase
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
      - HBASE_CONF_hbase_cluster_distributed=true
    depends_on:
      - namenode
      - datanode
      - zookeeper
    ports:
      - "16000:16000"
      - "16010:16010"
  
  hbase-regionserver:
    image: harisekhon/hbase:1.2
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    environment:
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
      - HBASE_CONF_hbase_cluster_distributed=true
    depends_on:
      - hbase-master
      - zookeeper
    ports:
      - "16020:16020"

####



volumes:
  namenode:
  datanode:
  hadoop_historyserver:


